### PR TITLE
add make restart

### PR DESCRIPTION
**Pull request by TomGoBravo**
`make restart` reloads the faust container only. This change lets projects see new faust application code in action without rebuilding the image or restarting kafka.
Add /repo_root_image (copy of the repo at container build time) and /repo_root_mount (mounted from live repo directory on the host) in the faust container.

### CODE REVIEW

**Comment by marcosschroh** [comment]
Hi,

Super nice how fast the worker is restarted. I think we should go for this approach until `Faust` has some kind of `dev server` to auto-reload changes in the code.

Regarding the changes made, I think we should try to keep clean the `wait_for_services.sh` because this `entrypoint` can be used for example with `k8s`. My idea is to have a `Dockerfile`, `Dockerfile.production`, `run_api.sh` and `run_production.sh`.

`Dockerfile.production` and `run_production.sh` should be the same as before because we don't want to reload changes in production.

Then, `Dockerfile` should be pretty similar to what to did except for the `CMD`:

```
CMD ["./wait_for_services.sh", "./run.sh"]
```
So, we can keep wait_for_services.sh the same as before.

Then for the `volumes` try to use the project slug, so we can reflect the same project structure inside the container. 

I think is going really well!

**Comment by TomGoBravo** [comment]
> Super nice how fast the worker is restarted. I think we should go for this approach until `Faust` has some kind of `dev server` to auto-reload changes in the code.

Well, even with auto reload we need the volume mount to get changes into the container and passing signals to the worker for a clean shutdown is nice.

> Regarding the changes made, I think we should try to keep clean the `wait_for_services.sh` because this `entrypoint` can be used for example with `k8s`. My idea is to have a `Dockerfile`, `Dockerfile.production`, `run_api.sh` and `run_production.sh`.

I thought removing the exec from `wait_for_services.sh` makes the behavior more closely match the name. With the exec I'd call it `wait_for_services_and_exec.sh`. I liked removing `entrypoint` and `command` from `docker-compose.yaml` so the image is started according to `Dockerfile` with or without compose.

What do you think of the dumb-init entry point? I'm pretty sure it'd work with k8s.

> `Dockerfile.production` and `run_production.sh` should be the same as before because we don't want to reload changes in production.

Oh, that's a good idea, though it does suggest mounting the repo volume at the same path as the repo in the image so dev and production paths are the same.

> Then, `Dockerfile` should be pretty similar to what to did except for the `CMD`:
> 
> ```
> CMD ["./wait_for_services.sh", "./run.sh"]
> ```

How about calling wait_for_services.sh from `run_dev.sh` and not calling it from `run_production.sh`? In my eyes that extracts all the interesting logic that is run in the container by default into one place, the run shell script. 

> Then for the `volumes` try to use the project slug, so we can reflect the same project structure inside the container.

The project slug still appears in the volume. Here is what I see in my container:
```
-rw-r--r-- 1 root   root   341 Apr 30 02:16 /repo_root_image/replay_output_experiment/app.py
-rw-r--r-- 1 myuser myuser 341 Apr 30 02:16 /repo_root_mount/replay_output_experiment/app.py
```
and on the host
```
-rw-r--r-- 1 tombrown tombrown 341 Apr 29 19:16 replay_repo_checkout/replay_output_experiment/app.py
```
though I totally get that the github repo is usually checked out to a directory with the project name. I do remember when I was getting started finding the nested directories with the same name kind of confusing.

There are some polish changes needed to this PR too. And perhaps it'd be easier to pull out the simple requirements change into a smaller PR but I'm out of time for this today :-(

**Comment by marcosschroh** [comment]
Hi @TomGoBravo ,

Ok, I can continue with this feature. Thanks for the  work done!!

**Comment by TomGoBravo** [comment]
That works for me, hope I've helped. Thank you for making this repo, it dramatically accelerated my learning about Kafka and introduced me to docker-compose.

**Comment by marcosschroh** [comment]
This in not longer need it because the `Faust app` is not built any more using `docker-compose`. For a better development experience is better to run the `kafka-cluster` with `docker-compose` and the `Faust app` in a `virtualenv`. In this way, the `Faust` worker can be restarted without restarting the whole cluster.

**Pull request closed without merging**
